// --- SCHEMAS ---
export * from './prompts/schemas/argumentAnalysis.schema';
export * from './prompts/schemas/continuation.schema';
export * from './prompts/schemas/draft.schema';
export * from './prompts/schemas/evidentiaryInconsistency.schema';
export * from './prompts/schemas/fracturePoint.schema';
export * from './prompts/schemas/integralAnalysis.schema';
export * from './prompts/schemas/jurisprudentialShielding.schema';
export * from './prompts/schemas/legalActionProposal.schema';
export * from './prompts/schemas/webSearchQuery.schema';
export * from './prompts/schemas/linkInsight.schema';
export * from './prompts/schemas/proposeAmendment.schema';
export * from './prompts/schemas/comparativeAnalysis.schema';
export * from './prompts/schemas/timeline.schema';
export * from './prompts/schemas/rag.schema';

// --- PROMPT GENERATORS ---
export * from './prompts/generators/argumentAnalysis.prompt';
export * from './prompts/generators/chat.prompt';
export * from './prompts/generators/continuationAnalysis.prompt';
export * from './prompts/generators/drafting.prompt';
export * from './prompts/generators/evidentiaryInconsistency.prompt';
export * from './prompts/generators/fracturePoint.prompt';
export * from './prompts/generators/imageAnalysis.prompt';
export * from './prompts/generators/integralAnalysis.prompt';
export * from './prompts/generators/jurisprudentialShielding.prompt';
export * from './prompts/generators/legalActionProposal.prompt';
export * from './prompts/generators/webSearch.prompt';
export * from './prompts/generators/linkInsight.prompt';
export * from './prompts/generators/proposeAmendment.prompt';
export * from './prompts/generators/integrateAmendment.prompt';
export * from './prompts/generators/comparativeAnalysis.prompt';
export * from './prompts/generators/timelineExtraction.prompt';
export * from './prompts/generators/rag.prompt';